language: java

jdk:
  - oraclejdk8
  
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

services:
  - docker

install: mvn install --quiet -DskipTests=true -Dmaven.javadoc.skip=true -B -V

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=rmortale/wildfly-mysql-app
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO

before_deploy:
  - sed -e "s/IMAGENAME/$REPO:travis-$TRAVIS_BUILD_NUMBER/" Dockerrun.template > Dockerrun.aws.json
  
